import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fetch from 'node-fetch'

export async function getServerSideProps(context) {
  const res = await fetch(`${process.env.API_SERVER_URL}/api/emojis`, {
    headers: {
      'Authorization': `Bearer ${process.env.API_TOKEN}`
    }
  })
  const data = await res.json()
  return {
    props: {
      emojis: data.data
    }
  }
}

export default function Home({ emojis }) {
  console.log(emojis)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido 🤠 a la búsqueda del 👑!!!
        </h1>

        <p className={styles.description}>
          Prueba suerte, pica un poco y a ver que encuentras...
        </p>

        <div className={styles.grid}>
          <ul>
            {emojis.map(emoji => <li key={emoji.id}><a href="/">{emoji.attributes.name} - {emoji.attributes.character}</a></li>)}
          </ul>
        </div>
      </main>
    </div>
  )
}
